# Generated by Django 3.2.8 on 2021-10-28 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField(null=True)),
                ('short_distribution', models.CharField(max_length=300)),
                ('distribution', models.TextField(null=True)),
                ('is_exist', models.BooleanField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_account.account')),
            ],
        ),
    ]
