# Generated by Django 3.2.8 on 2021-11-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pic',
            field=models.ImageField(null=True, upload_to='', verbose_name='image'),
        ),
    ]
